### ISSUE TITLE
Rails 7.1 does not have a `unwrapped_html_escape` method where it is expected

### ISSUE THREAD

**Issue by begerdom** [makandra/angular_xss#12]
Rails 7.1 changed the way that the `unwrapped_html_escape`-method is defined: https://github.com/rails/rails/commit/d6c42b3fba456d1882682a5348610309164b1edd

It is now prepended over a separate module. I cannot load the application with the current version as the method is not found.

```
NameError: method `unwrapped_html_escape' not defined in #<Class:#<NilClass:0x0000000000000004>> (NameError)
web_1                       | 
web_1                       |     singleton_class.send(:remove_method, :unwrapped_html_escape)
web_1                       |                    ^^^^^
web_1                       | /persistent/bundle/ruby/3.2.0/gems/angular_xss-0.4.1/lib/angular_xss/erb.rb:18:in `remove_method'
```

**Comment by makmic** [comment]
Hi @begerdom,
we'll look into this issue and try to add Rails 7.1 compatibility to the gem soon

**Comment by makmic** [comment]
Resolved via https://github.com/makandra/angular_xss/pull/13
